language: haskell
ghc: 7.8

before_install:
  - cabal install happy regex-posix hlint hspec xml

install:
  - runhaskell Setup.hs configure --enable-tests --enable-library-coverage --user

script:
  - runhaskell Setup.hs build
  - runhaskell Setup.hs test
