language: haskell
ghc: 7.8

before_install:
  - cabal clean
  - rm -rf ~/.ghc ~/.cabal
  - rm -rf ./.cabal-sandbox/ ./cabal.sandbox.config
  - cabal sandbox init
  - cabal update
  - cabal install happy
  - cat /home/travis/build/decomputed/euler/.cabal-sandbox/logs/happy-1.19.5.log
  - cabal install alex

install:
  - ghc --version
  - cabal --version
  - happy --version
  - alex --version

script:
  - cabal install --only-dependencies --enable-tests
  - cat /home/travis/build/decomputed/euler/.cabal-sandbox/logs/haskell-src-exts-1.16.0.1.log
  - cabal build
  - cabal test