language: haskell
ghc: 7.8

before_install:
  - cabal install happy regex-posix hlint hspec

install:
  - runhaskell Setup.hs configure --enable-tests --user

script:
  - runhaskell Setup.hs build
  - runhaskell Setup.hs test
