language: haskell
ghc: 7.8

before_install:
  - cabal clean
  - rm -rf ~/.ghc ~/.cabal
  - rm -rf ./.cabal-sandbox/ ./cabal.sandbox.config
  - cabal update
  - cabal install cabal-install
  -  ~/.cabal/bin/cabal --version
  -  ~/.cabal/bin/cabal install happy
  - happy --version
  -  ~/.cabal/bin/cabal install alex
  - alex --version

install:
  - ghc --version

script:
  -  ~/.cabal/bin/cabal install --only-dependencies --enable-tests
  - cat /home/travis/build/decomputed/euler/.cabal-sandbox/logs/haskell-src-exts-1.16.0.1.log
  -  ~/.cabal/bin/cabal build
  -  ~/.cabal/bin/cabal test