language: haskell
ghc: 7.8

before_install:
  - whoami
  - echo $HOME
  - sudo apt-get update
  - sudo apt-get install -y happy alex
  - cabal clean
  - rm -rf ~/.ghc ~/.cabal
  - rm -rf ./.cabal-sandbox/ ./cabal.sandbox.config
  - cabal sandbox init
  - cabal update

install:
  - ghc --version
  - cabal --version
  - happy --version
  - alex --version

script:
  - cabal install --only-dependencies --enable-tests
  - cabal build
  - cabal test