language: haskell
ghc: 7.8

before_install:
  - cabal install cabal-install
  - ~/.cabal/bin/cabal install happy
  - ~/.cabal/bin/cabal install alex

install:
  - ~/.cabal/bin/cabal install --only-dependencies --enable-tests

script:
  - ~/.cabal/bin/cabal build
  - ~/.cabal/bin/cabal test