language: haskell
ghc: 7.8

before_install:
  - cabal install cabal-install
  - ~/.cabal/bin/cabal install happy

install:
  - ~/.cabal/bin/cabal install --only-dependencies --enable-tests --enable-library-coverage

script:
  - ~/.cabal/bin/cabal build
  - ~/.cabal/bin/cabal test
